(() => {
'use strict';

const regions = {
  pfc:{name:'Prefrontal cortex',pos:[0,.35,1.95],size:.68,desc:'A major executive-control system involved in planning, decision making, working memory, attention and regulation of behavior and emotion.',tags:['Executive control','Planning','Working memory','Regulation'],links:['Amygdala','Anterior cingulate cortex','Hippocampus','Basal ganglia']},
  amygdala:{name:'Amygdala',pos:[-.72,-.18,.35],size:.31,desc:'A set of nuclei important for detecting and learning about biologically and emotionally significant stimuli, especially threat and reward relevance.',tags:['Salience','Threat learning','Emotional learning','Valence'],links:['Hypothalamus','Hippocampus','Prefrontal cortex','Brainstem']},
  hippocampus:{name:'Hippocampus',pos:[-.96,-.30,.02],size:.29,desc:'Central to forming and retrieving episodic memories and representing context. It helps distinguish what is happening now from what happened before.',tags:['Memory','Context','Spatial representation'],links:['Amygdala','Prefrontal cortex','Thalamus']},
  hypothalamus:{name:'Hypothalamus',pos:[0,-.53,.12],size:.27,desc:'A small but powerful regulator linking brain signals to homeostasis, autonomic control and endocrine function.',tags:['Homeostasis','Autonomic control','Endocrine control','Hunger'],links:['Pituitary','Brainstem','Limbic circuits']},
  thalamus:{name:'Thalamus',pos:[0,.01,-.16],size:.39,desc:'A major relay and integration hub for sensory and motor information and communication with widespread cortical systems.',tags:['Relay','Integration','Arousal'],links:['Cortex','Basal ganglia','Brainstem']},
  insula:{name:'Insula',pos:[-1.42,.04,.67],size:.29,desc:'Involved in interoception—the representation of internal bodily states—and in integrating bodily signals with salience and emotion.',tags:['Interoception','Salience','Body awareness'],links:['Anterior cingulate cortex','Hypothalamus','Autonomic systems']},
  acc:{name:'Anterior cingulate cortex',pos:[-.15,.56,1.40],size:.34,desc:'Supports cognitive control, conflict monitoring, motivation and integration of emotional and cognitive information.',tags:['Control','Conflict','Motivation','Salience'],links:['Prefrontal cortex','Insula','Limbic systems']},
  nacc:{name:'Nucleus accumbens',pos:[.54,-.27,.56],size:.24,desc:'Part of the ventral striatal system involved in reward processing, motivation and reinforcement learning.',tags:['Reward','Motivation','Reinforcement'],links:['Prefrontal cortex','Dopamine systems','Limbic circuits']},
  basal:{name:'Basal ganglia',pos:[.65,.08,.05],size:.46,desc:'Interconnected nuclei important for action selection, movement, habits, procedural learning and reward-related behavior.',tags:['Action selection','Movement','Habits','Learning'],links:['Cortex','Thalamus','Dopamine systems']},
  brainstem:{name:'Brainstem',pos:[0,-1.15,-.42],size:.44,desc:'Connects brain and spinal cord and contains circuits involved in arousal, breathing, cardiovascular regulation and many basic life-support functions.',tags:['Arousal','Breathing','Cardiovascular','Reflexes'],links:['Hypothalamus','Spinal cord','Cerebellum']},
  cerebellum:{name:'Cerebellum',pos:[1.16,-.76,-.54],size:.58,desc:'Coordinates movement and balance and also contributes to timing, prediction and some cognitive processes.',tags:['Coordination','Balance','Timing','Prediction'],links:['Brainstem','Motor cortex','Spinal pathways']},
  motor:{name:'Motor cortex',pos:[-.50,.69,1.08],size:.43,desc:'A key cortical system for planning and executing voluntary movement.',tags:['Movement','Motor planning'],links:['Basal ganglia','Cerebellum','Spinal cord']},
  sensory:{name:'Somatosensory cortex',pos:[.46,.68,1.04],size:.41,desc:'Represents touch, proprioception and other bodily sensory information and contributes to conscious body perception.',tags:['Touch','Proprioception','Body map'],links:['Thalamus','Insula','Motor cortex']},
  visual:{name:'Visual cortex',pos:[0,.16,-1.84],size:.47,desc:'Processes visual information and supports perception of objects, motion, spatial relationships and visual scenes.',tags:['Vision','Perception','Scene processing'],links:['Thalamus','Association cortex']},
  corpus:{name:'Corpus callosum',pos:[0,.25,.12],size:.21,desc:'A large fiber tract connecting the cerebral hemispheres and allowing information to pass between them.',tags:['Interhemispheric communication'],links:['Widespread cortical regions']}
};

const states = {
  Neutral:{explain:'A neutral baseline is a useful reference—not a literal “resting brain” measurement.',body:'Balanced autonomic and attentional demands; no single response system is being emphasized in this educational model.',base:{pfc:52,amygdala:28,hippocampus:48,hypothalamus:35,thalamus:45,insula:38,acc:42,nacc:38,basal:44,brainstem:40,cerebellum:45,motor:40,sensory:40,visual:38,corpus:35}},
  Fear:{explain:'Threat processing involves distributed circuits linking salience, context, autonomic control and executive regulation.',body:'Threat-related processing can recruit autonomic and endocrine responses, alter attention toward salient cues and prepare defensive behavior.',base:{pfc:38,amygdala:88,hippocampus:62,hypothalamus:78,thalamus:68,insula:76,acc:72,nacc:22,basal:40,brainstem:82,cerebellum:42,motor:58,sensory:70,visual:68,corpus:35}},
  Stress:{explain:'Acute stress is a coordinated brain–body response. Chronic stress is more complex and depends on duration, context and individual differences.',body:'Stress can engage sympathetic/autonomic and endocrine systems, changing heart rate, vigilance, energy allocation and digestion.',base:{pfc:42,amygdala:78,hippocampus:55,hypothalamus:86,thalamus:62,insula:72,acc:68,nacc:28,basal:40,brainstem:76,cerebellum:44,motor:50,sensory:58,visual:60,corpus:35}},
  Anger:{explain:'Anger is not located in one structure. Threat, salience, action selection, valuation and regulation all interact.',body:'High arousal can increase autonomic activation and mobilize energy for action; cognition and context strongly shape the resulting behavior.',base:{pfc:46,amygdala:82,hippocampus:45,hypothalamus:70,thalamus:58,insula:67,acc:62,nacc:48,basal:62,brainstem:72,cerebellum:45,motor:66,sensory:55,visual:55,corpus:35}},
  Joy:{explain:'Reward and positive emotion recruit interacting valuation, motivation, memory and regulatory systems.',body:'Positive affect can accompany changes in motivation, attention, autonomic state and social behavior.',base:{pfc:65,amygdala:45,hippocampus:55,hypothalamus:50,thalamus:48,insula:55,acc:60,nacc:84,basal:68,brainstem:48,cerebellum:50,motor:55,sensory:55,visual:52,corpus:35}},
  Sadness:{explain:'Sadness involves memory, appraisal, bodily state and motivational systems rather than a single “sadness center.”',body:'Sadness can change motivation, attention, social behavior and bodily state; responses vary considerably by context and person.',base:{pfc:52,amygdala:58,hippocampus:70,hypothalamus:45,thalamus:48,insula:62,acc:65,nacc:28,basal:36,brainstem:42,cerebellum:40,motor:32,sensory:42,visual:48,corpus:35}},
  Love:{explain:'Romantic attachment involves reward, motivation, social cognition, memory and bodily systems.',body:'Attachment and social reward can influence autonomic state, attention, motivation and memory for socially meaningful experiences.',base:{pfc:62,amygdala:52,hippocampus:60,hypothalamus:58,thalamus:48,insula:58,acc:64,nacc:82,basal:65,brainstem:52,cerebellum:42,motor:44,sensory:52,visual:55,corpus:35}},
  Focus:{explain:'Attention depends on coordinated control, arousal, sensory processing and motivation.',body:'Focused attention changes the allocation of processing resources; arousal and motivation help determine how sustainable focus is.',base:{pfc:84,amygdala:26,hippocampus:58,hypothalamus:34,thalamus:60,insula:46,acc:76,nacc:44,basal:56,brainstem:44,cerebellum:48,motor:40,sensory:50,visual:58,corpus:35}},
  Motivation:{explain:'Motivation emerges from valuation, reward prediction, executive control and action-selection systems.',body:'Motivation links anticipated outcomes to action selection, effort and learning, with bodily arousal supporting action.',base:{pfc:70,amygdala:42,hippocampus:50,hypothalamus:48,thalamus:46,insula:45,acc:68,nacc:88,basal:72,brainstem:50,cerebellum:46,motor:56,sensory:46,visual:50,corpus:35}}
};

const factors = {
  'Sleep deprivation':{mods:{pfc:-18,amygdala:14,hippocampus:-10,acc:-12,insula:6},body:'Reduced sleep can impair attention and executive control and alter emotional reactivity.'},
  'Acute exercise':{mods:{pfc:5,nacc:8,basal:10,brainstem:8},body:'Exercise changes arousal, autonomic state and neuromodulatory signaling; effects depend on intensity and individual context.'},
  'Meditation':{mods:{pfc:8,amygdala:-10,insula:7,acc:8},body:'Meditation practices can influence attention and emotional regulation; effects vary substantially by practice and person.'},
  'Caffeine':{mods:{pfc:6,brainstem:8,thalamus:5},body:'Caffeine increases alertness by antagonizing adenosine receptors; sensitivity and effects vary.'},
  'Hunger':{mods:{hypothalamus:22,insula:12,nacc:10,pfc:-5},body:'Energy status is monitored by hypothalamic and peripheral signals that influence motivation and behavior.'},
  'Social rejection':{mods:{amygdala:12,insula:18,acc:14,nacc:-10,pfc:-4},body:'Social threat can recruit salience, interoceptive and control systems; context strongly influences responses.'},
  'Novelty':{mods:{hippocampus:10,thalamus:8,nacc:14,acc:10},body:'Novel events recruit attention, learning and valuation systems.'},
  'Chronic stress':{mods:{pfc:-20,amygdala:16,hypothalamus:15,hippocampus:-12,insula:12,acc:-10},body:'Longer-term stress exposure can affect multiple regulatory systems; human effects are heterogeneous and depend on duration and context.'}
};

const networks = {
  'Threat & salience':{regions:['amygdala','insula','acc','hypothalamus','brainstem'],desc:'Detects and prioritizes biologically relevant signals and coordinates defensive or adaptive responses.'},
  'Executive control':{regions:['pfc','acc','thalamus','basal'],desc:'Supports planning, working memory, conflict monitoring, attention and flexible behavior.'},
  'Reward & motivation':{regions:['nacc','basal','pfc','amygdala'],desc:'Links expected outcomes with motivation, learning, effort and action selection.'},
  'Memory & context':{regions:['hippocampus','pfc','amygdala','thalamus'],desc:'Builds relationships among events, context, emotion and prior experience.'},
  'Body awareness':{regions:['insula','thalamus','acc','hypothalamus','brainstem'],desc:'Integrates internal bodily signals with emotion, attention and homeostatic control.'}
};

const lessons = {
  distributed:'Fear, reward, attention and other experiences arise from coordinated activity across multiple interacting systems. A single-region explanation is usually an oversimplification.',
  context:'The same sensory input can mean different things depending on memory, expectations, bodily state and the surrounding situation.',
  body:'The brain continuously receives information from the body and sends signals that alter autonomic, endocrine and motor state. Emotion is not purely “in the head.”',
  plasticity:'Learning and experience can alter synaptic strength, connectivity and functional organization. Plasticity occurs throughout life, although mechanisms differ across development and systems.',
  uncertainty:'Brain imaging measures proxies such as blood flow or metabolism. It does not directly display a specific emotion or thought as a colored light.'
};

const state = {emotion:'Neutral',intensity:70,timeline:2,selected:'pfc',mods:new Set(),view:'explore',showRegions:true,showLinks:true,showLabels:false,rotX:-.06,rotY:.18,zoom:1,drag:false,lastX:0,lastY:0,downX:0,downY:0};
const canvas=document.getElementById('brainCanvas'),ctx=canvas.getContext('2d');
const stage=document.getElementById('brainStage');
let dpr=1,w=0,h=0,brainPoints=[],regionDots={},hovered=null;

function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(window.devicePixelRatio||1,2);w=r.width;h=r.height;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);makeBrainPoints();draw();}
window.addEventListener('resize',resize);

function mul(a,b){return [a[0]*b[0]-a[1]*b[2]+a[2]*b[1],a[0]*b[2]+a[1]*b[0]-a[2]*b[1],a[2]*b[2]+a[0]*b[1]-a[1]*b[0]]}
function rotate(p,rx,ry){let [x,y,z]=p;const cx=Math.cos(rx),sx=Math.sin(rx),cy=Math.cos(ry),sy=Math.sin(ry);let y1=y*cx-z*sx,z1=y*sx+z*cx;let x2=x*cy-z1*sy,z2=x*sy+z1*cy;return [x2,y1,z2]}
function project(p){const q=rotate(p,state.rotX,state.rotY),s=145*state.zoom/(6.4-q[2]);return {x:w/2+q[0]*s,y:h/2-q[1]*s,z:q[2],s};}
function makeBrainPoints(){brainPoints=[];const N=2600;for(let i=0;i<N;i++){const side=i%2?-1:1,u=Math.random()*Math.PI*2,v=Math.acos(2*Math.random()-1);let x=side*(1.0+Math.random()*.98), y=Math.cos(v)*1.72, z=Math.sin(v)*Math.cos(u)*1.66; // hemisphere scaffold
x*=.94; y*=.93; z*=.98;
const folds=.08*Math.sin(u*18+v*7)+.045*Math.sin(u*31-v*11)+.025*Math.cos(v*35);const rr=1+folds; x*=rr;y*=rr;z*=rr; if(Math.random()<.14)y-=.16; brainPoints.push({p:[x,y+.12,z],a:.16+Math.random()*.28,sz:.45+Math.random()*1.25,side});}}

function color(v){const t=Math.max(0,Math.min(1,v/100));const r=Math.round(75+180*t),g=Math.round(145-60*t),b=Math.round(176-55*t);return `rgb(${r},${g},${b})`;}
function score(id){let v=states[state.emotion].base[id]??45;v=45+(v-45)*(state.intensity/70);for(const f of state.mods)v+=factors[f].mods[id]||0;return Math.max(8,Math.min(96,Math.round(v)));}
function radiusFor(id){return regions[id].size*35*state.zoom;}
function drawBrainShell(){const pts=brainPoints.slice().sort((a,b)=>rotate(a.p,state.rotX,state.rotY)[2]-rotate(b.p,state.rotX,state.rotY)[2]);for(const pt of pts){const p=project(pt.p);const depth=Math.max(.28,Math.min(1,(p.z+2.2)/4.4));ctx.fillStyle=`rgba(154,169,183,${pt.a*(.35+.65*depth)})`;ctx.beginPath();ctx.arc(p.x,p.y,pt.sz*state.zoom,0,Math.PI*2);ctx.fill();}}
function line(a,b,alpha=.22){const pa=project(regions[a].pos),pb=project(regions[b].pos);ctx.strokeStyle=`rgba(120,155,180,${alpha})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();}
const links=[['amygdala','hypothalamus'],['amygdala','hippocampus'],['amygdala','pfc'],['pfc','acc'],['pfc','nacc'],['pfc','basal'],['hippocampus','thalamus'],['insula','acc'],['insula','hypothalamus'],['hypothalamus','brainstem'],['thalamus','pfc'],['thalamus','basal'],['basal','motor'],['brainstem','cerebellum'],['sensory','thalamus'],['visual','thalamus']];
function drawConnections(){if(!state.showLinks)return;for(const [a,b] of links){const va=score(a),vb=score(b);line(a,b,.09+((va+vb)/200)*.28)}}
function drawRegions(){const items=Object.entries(regions).map(([id,r])=>({id,r,p:project(r.pos)})).sort((a,b)=>a.p.z-b.p.z);regionDots={};for(const it of items){if(!state.showRegions)continue;const v=score(it.id),rad=Math.max(4,radiusFor(it.id));const selected=it.id===state.selected;ctx.globalAlpha=selected?1:.82;ctx.fillStyle=color(v);ctx.shadowBlur=selected?16:8;ctx.shadowColor=color(v);ctx.beginPath();ctx.arc(it.p.x,it.p.y,rad,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(selected){ctx.strokeStyle='#eaf7ff';ctx.lineWidth=2;ctx.stroke()}regionDots[it.id]={x:it.p.x,y:it.p.y,r:rad,z:it.p.z};if(state.showLabels||selected){ctx.fillStyle='#dce8f0';ctx.font=selected?'600 11px system-ui':'10px system-ui';ctx.textAlign='center';ctx.fillText(it.r.name,it.p.x,it.p.y-rad-6)}}ctx.globalAlpha=1}
function draw(){if(!ctx)return;ctx.clearRect(0,0,w,h);drawBrainShell();drawConnections();drawRegions();drawBodyGlow();}
function drawBodyGlow(){const center=project([0,0,0]);const grd=ctx.createRadialGradient(center.x,center.y,20,center.x,center.y,260);grd.addColorStop(0,'rgba(125,211,252,.05)');grd.addColorStop(1,'rgba(125,211,252,0)');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(center.x,center.y,260,0,Math.PI*2);ctx.fill();}
function pick(x,y){let best=null,bd=Infinity;for(const [id,d] of Object.entries(regionDots)){const dx=x-d.x,dy=y-d.y,dist=Math.hypot(dx,dy);if(dist<d.r+9&&dist<bd){best=id;bd=dist}}return best;}
canvas.addEventListener('pointerdown',e=>{state.drag=true;state.lastX=e.clientX;state.lastY=e.clientY;state.downX=e.clientX;state.downY=e.clientY;canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(state.drag){state.rotY+=(e.clientX-state.lastX)*.008;state.rotX+=(e.clientY-state.lastY)*.008;state.rotX=Math.max(-1.25,Math.min(1.25,state.rotX));state.lastX=e.clientX;state.lastY=e.clientY;draw()}else{const r=canvas.getBoundingClientRect();hovered=pick(e.clientX-r.left,e.clientY-r.top);canvas.style.cursor=hovered?'pointer':'grab'}});
canvas.addEventListener('pointerup',e=>{const r=canvas.getBoundingClientRect();if(!state.drag)return;const moved=Math.hypot(e.clientX-state.downX,e.clientY-state.downY);state.drag=false;const hit=pick(e.clientX-r.left,e.clientY-r.top);if(hit && moved<8){selectRegion(hit)}});
canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom*=e.deltaY<0?1.08:.92;state.zoom=Math.max(.72,Math.min(1.75,state.zoom));draw()},{passive:false});

function selectRegion(id){if(!regions[id])return;state.selected=id;renderInspector();draw();}
function setEmotion(emotion){if(!states[emotion])return;state.emotion=emotion;document.getElementById('stateChip').textContent=`${emotion.toUpperCase()} · ${state.intensity}%`;renderInspector();draw();}
function syncIntensity(v){state.intensity=Math.max(0,Math.min(100,Number(v)||0));document.getElementById('stateChip').textContent=`${state.emotion.toUpperCase()} · ${state.intensity}%`;draw();renderDrawer();}
function tagHTML(arr){return arr.map(x=>`<span class="tag">${x}</span>`).join('')}
function renderInspector(){const r=regions[state.selected],v=score(state.selected);document.getElementById('inspectContent').innerHTML=`<div class="inspect-card"><div class="eyebrow">SELECTED STRUCTURE</div><h2>${r.name}</h2><p>${r.desc}</p><div class="section-title">CURRENT CONCEPTUAL ACTIVITY</div><div class="meter-row"><span>Relative signal</span><b>${v}</b></div><div class="meter"><i style="width:${v}%"></i></div><div class="section-title">KEY FUNCTIONS</div><div class="tags">${tagHTML(r.tags)}</div><div class="section-title">CONNECTED SYSTEMS</div><div class="connection-list">${r.links.map(name=>`<button type="button" data-link="${name}">${name}</button>`).join('')}</div><div class="section-title">WHY IT CHANGES</div><div class="callout">In the <b>${state.emotion}</b> state, this visualization assigns ${v}/100 relative engagement. Change intensity or scenario factors to see the conceptual model shift.</div><div class="section-title">SCIENTIFIC STATUS</div><div class="tags"><span class="tag">Educational model</span><span class="tag">Network-level evidence</span><span class="tag">Not diagnostic</span></div></div>`;document.querySelectorAll('[data-link]').forEach(btn=>btn.addEventListener('click',()=>{const target=Object.entries(regions).find(([,x])=>x.name===btn.dataset.link);if(target)selectRegion(target[0])}));}

function timelineLabel(){return ['Milliseconds','Seconds','Minutes','Hours','Days → months'][state.timeline]}
function neurochemistry(){
  const map={
    Neutral:['Dopamine · baseline context','Norepinephrine · baseline context','Serotonin · broad regulatory context'],
    Fear:['Norepinephrine · arousal/attention association','Adrenaline/epinephrine · peripheral stress response','Cortisol · endocrine stress response'],
    Stress:['Norepinephrine · arousal/attention association','Cortisol · HPA-axis stress response','Adrenaline/epinephrine · acute sympathetic response'],
    Anger:['Norepinephrine · arousal/attention association','Dopamine · motivation/action context','Cortisol · stress context'],
    Joy:['Dopamine · reward/motivation association','Endogenous opioids · pleasure/reinforcement context','Serotonin · broad regulatory context'],
    Sadness:['Serotonin · broad regulatory context','Norepinephrine · arousal/motivation context','Cortisol · stress context'],
    Love:['Oxytocin · social/attachment association','Dopamine · reward/motivation association','Endogenous opioids · attachment/pleasure context'],
    Focus:['Norepinephrine · attention/arousal association','Dopamine · cognitive control/motivation association','Acetylcholine · attention/learning association'],
    Motivation:['Dopamine · reward prediction/motivation association','Norepinephrine · arousal/effort context','Acetylcholine · learning/attention association']
  };
  return map[state.emotion]||map.Neutral;
}
function timelineExplanation(){
  return [
    'Milliseconds: rapid sensory and neural signaling dominates the teaching model.',
    'Seconds: salience, autonomic response and attention can rapidly reshape behavior.',
    'Minutes: endocrine and sustained arousal processes become more relevant.',
    'Hours: sleep, energy balance, learning and repeated exposure begin to matter more.',
    'Days → months: adaptation, learning, context and plasticity become central; this is not a direct activity prediction.'
  ][state.timeline];
}
function openDrawer(kind){state.view=kind;const drawer=document.getElementById('drawer');drawer.classList.add('open');renderDrawer();}
function closeDrawer(){document.getElementById('drawer').classList.remove('open')}
function renderDrawer(){const title=document.getElementById('drawerTitle'),eyebrow=document.getElementById('drawerEyebrow'),out=document.getElementById('drawerContent');if(state.view==='states'){eyebrow.textContent='STATE LAB';title.textContent='Emotional states';out.innerHTML=`<div class="state-grid">${Object.keys(states).map(s=>`<button class="choice ${s===state.emotion?'selected':''}" data-emotion="${s}"><b>${s}</b><small>${states[s].explain}</small></button>`).join('')}</div><div class="slider-row"><span class="eyebrow">INTENSITY</span><input id="drawerIntensity" type="range" min="0" max="100" value="${state.intensity}"><span class="slider-value" id="drawerIntensityValue">${state.intensity}%</span></div><div class="slider-row"><span class="eyebrow">TIME SCALE</span><input id="drawerTimeline" type="range" min="0" max="4" step="1" value="${state.timeline}"><span class="slider-value" id="drawerTimelineValue">${timelineLabel()}</span></div><div class="state-detail"><div class="drawer-card"><h3>Brain → body</h3><p>${states[state.emotion].body}</p></div><div class="drawer-card"><h3>Time changes the question</h3><p>${timelineExplanation()}</p></div></div><div class="drawer-grid"><div class="drawer-card"><h3>Neuromodulatory context</h3><p>${neurochemistry().map(x=>'• '+x).join('<br>')}</p></div><div class="drawer-card"><h3>Interpretation</h3><p>These are educational associations among systems, not neurotransmitter measurements. A real person's neurochemistry cannot be inferred from this interface.</p></div><div class="drawer-card"><h3>Evidence level</h3><p><b>Supported / simplified model.</b> Brain-state relationships are distributed, context-dependent and probabilistic.</p></div></div>`;document.querySelectorAll('[data-emotion]').forEach(b=>b.addEventListener('click',()=>{setEmotion(b.dataset.emotion);renderDrawer()}));document.getElementById('drawerIntensity').addEventListener('input',e=>{syncIntensity(e.target.value);document.getElementById('drawerIntensityValue').textContent=state.intensity+'%'});document.getElementById('drawerTimeline').addEventListener('input',e=>{state.timeline=Number(e.target.value);document.getElementById('drawerTimelineValue').textContent=timelineLabel();renderDrawer()});}
else if(state.view==='scenarios'){eyebrow.textContent='SCENARIO BUILDER';title.textContent='Change the conditions';out.innerHTML=`<p class="muted">Combine internal and external factors. The model updates the same brain state rather than inventing a separate “stress brain.”</p><div class="factor-grid">${Object.keys(factors).map(f=>`<button class="choice ${state.mods.has(f)?'selected':''}" data-factor="${f}"><b>${f}</b><small>${factors[f].body}</small></button>`).join('')}</div><div class="scenario-summary"><div class="drawer-card"><h3>Scenario readout</h3><p>${state.mods.size?[...state.mods].join(' + '):'No modifiers selected.'}</p><p style="margin-top:7px">${state.mods.size?[...state.mods].map(f=>factors[f].body).join(' '):'Add one or more factors to see how context changes the conceptual network.'}</p></div></div>`;document.querySelectorAll('[data-factor]').forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.factor;state.mods.has(f)?state.mods.delete(f):state.mods.add(f);renderDrawer();renderInspector();draw()}));}
else if(state.view==='networks'){eyebrow.textContent='SYSTEMS VIEW';title.textContent='Brain networks';out.innerHTML=`<p class="muted">Complex behavior emerges from interacting systems—not one “emotion center.” Select a network to highlight its member structures.</p><div class="network-grid">${Object.entries(networks).map(([n,x])=>`<button class="choice" data-network="${n}"><b>${n}</b><small>${x.desc}</small><div class="tags" style="margin-top:8px">${tagHTML(x.regions.map(id=>regions[id].name))}</div></button>`).join('')}</div>`;document.querySelectorAll('[data-network]').forEach(b=>b.addEventListener('click',()=>{const n=networks[b.dataset.network];selectRegion(n.regions[0]);closeDrawer();document.querySelectorAll('.quick-row button').forEach(x=>x.classList.remove('active'))}));}
else if(state.view==='learn'){eyebrow.textContent='LEARNING MODE';title.textContent='Build intuition';out.innerHTML=`<div class="lesson-grid">${Object.entries(lessons).map(([k,v])=>`<button class="choice" data-lesson="${k}"><b>${({distributed:'Distributed processing',context:'Context matters',body:'Brain ↔ body loop',plasticity:'Plasticity',uncertainty:'Evidence & uncertainty'})[k]}</b><small>${v}</small></button>`).join('')}</div><div class="state-detail"><div class="drawer-card"><h3>Evidence language</h3><p><b>Established</b> — strong converging evidence. <b>Supported</b> — evidence is substantial but context-dependent. <b>Simplified model</b> — intentionally compressed for learning. <b>Research uncertainty</b> — active area of investigation.</p></div><div class="drawer-card"><h3>Important limitation</h3><p>NeuroAtlas visualizes relationships among systems. It does not claim that one structure produces one emotion or that colors represent a person's actual neural activity.</p></div></div><div class="callout" id="lessonCallout" style="margin-top:10px">Select a concept above.</div>`;document.querySelectorAll('[data-lesson]').forEach(b=>b.addEventListener('click',()=>document.getElementById('lessonCallout').textContent=lessons[b.dataset.lesson]));}}

function setView(v){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='explore'){closeDrawer();document.getElementById('pageTitle').textContent='Explore the brain';document.getElementById('pageSubtitle').textContent='Rotate the model, select a structure, or choose an emotional state.'}else{document.getElementById('pageTitle').textContent=({states:'Emotional states',scenarios:'Scenario builder',networks:'Brain networks',learn:'Learn'})[v];document.getElementById('pageSubtitle').textContent=({states:'Tune an emotional state and watch multiple systems change together.',scenarios:'Combine internal and external factors to explore context.',networks:'Explore coordinated systems rather than isolated brain regions.',learn:'Build a mental model of how brain, body and behavior interact.'})[v];openDrawer(v)}}

document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
document.querySelectorAll('.quick-row button').forEach(b=>b.addEventListener('click',()=>{setEmotion(b.dataset.state);document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='explore'));closeDrawer()}));
document.getElementById('toggleRegions').addEventListener('click',e=>{state.showRegions=!state.showRegions;e.currentTarget.classList.toggle('active',state.showRegions);draw()});
document.getElementById('toggleLinks').addEventListener('click',e=>{state.showLinks=!state.showLinks;e.currentTarget.classList.toggle('active',state.showLinks);draw()});
document.getElementById('toggleLabels').addEventListener('click',e=>{state.showLabels=!state.showLabels;e.currentTarget.classList.toggle('active',state.showLabels);draw()});
document.getElementById('resetCamera').addEventListener('click',()=>{state.rotX=-.06;state.rotY=.18;state.zoom=1;draw()});
document.getElementById('closeDrawer').addEventListener('click',closeDrawer);
document.getElementById('helpBtn').addEventListener('click',()=>document.getElementById('helpModal').classList.remove('hidden'));
document.getElementById('closeHelp').addEventListener('click',()=>document.getElementById('helpModal').classList.add('hidden'));
document.getElementById('helpModal').addEventListener('click',e=>{if(e.target.id==='helpModal')e.currentTarget.classList.add('hidden')});
document.getElementById('resetAll').addEventListener('click',()=>{state.emotion='Neutral';state.intensity=70;state.timeline=2;state.selected='pfc';state.mods.clear();state.rotX=-.06;state.rotY=.18;state.zoom=1;state.showRegions=true;state.showLinks=true;state.showLabels=false;document.querySelectorAll('.control').forEach(x=>x.classList.remove('active'));document.getElementById('toggleRegions').classList.add('active');document.getElementById('toggleLinks').classList.add('active');renderInspector();draw();closeDrawer()});
const search=document.getElementById('search');const results=document.getElementById('searchResults');search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();if(!q){results.innerHTML='';return}const found=Object.entries(regions).filter(([,r])=>r.name.toLowerCase().includes(q)).slice(0,6);results.innerHTML=found.map(([id,r])=>`<button class="search-result" data-search-id="${id}">${r.name}</button>`).join('');document.querySelectorAll('[data-search-id]').forEach(b=>b.addEventListener('click',()=>{selectRegion(b.dataset.searchId);search.value='';results.innerHTML=''}))});

renderInspector();resize();
})();
