import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';

const MODEL_URL='https://cdn.jsdelivr.net/gh/itayinbarr/brainproject@main/brain-atlas/models/brain.glb';
const DRACO_URL='https://www.gstatic.com/draco/versioned/decoders/1.5.7/';

const anatomy={
  pfc:{name:'Prefrontal cortex',terms:['prefrontal','frontal pole','rostral middle frontal','caudal middle frontal','orbitofrontal','rostral anterior cingulate','superior frontal'],roles:['Planning','Decision making','Working memory','Regulation'],desc:'Supports planning, flexible decision making, working memory and regulation of behavior.'},
  amygdala:{name:'Amygdala',terms:['amygdala','amygdaloid'],roles:['Salience','Threat learning','Emotional learning'],desc:'Helps detect and learn about emotionally significant stimuli, including threat and reward relevance.'},
  hippocampus:{name:'Hippocampus',terms:['hippocampus'],roles:['Memory','Context','Spatial representation'],desc:'Supports episodic memory and context, helping relate present events to prior experience.'},
  hypothalamus:{name:'Hypothalamus',terms:['hypothalamus'],roles:['Homeostasis','Autonomic control','Endocrine control'],desc:'Links brain signals with homeostasis, autonomic regulation and endocrine control.'},
  thalamus:{name:'Thalamus',terms:['thalamus'],roles:['Relay','Integration','Arousal'],desc:'A major relay and integration hub connecting sensory, motor and widespread cortical systems.'},
  insula:{name:'Insula',terms:['insula'],roles:['Interoception','Salience','Body awareness'],desc:'Represents internal bodily states and integrates those signals with salience and emotion.'},
  acc:{name:'Anterior cingulate cortex',terms:['anterior cingulate','rostral anterior cingulate','caudal anterior cingulate'],roles:['Control','Conflict','Motivation','Salience'],desc:'Supports cognitive control, conflict monitoring, motivation and integration of emotion with cognition.'},
  nacc:{name:'Nucleus accumbens',terms:['nucleus accumbens','accumbens'],roles:['Reward','Motivation','Reinforcement'],desc:'Part of the ventral striatal system involved in reward, motivation and reinforcement learning.'},
  basal:{name:'Basal ganglia',terms:['caudate','putamen','globus pallidus','lentiform nucleus','basal ganglia','subthalamic','substantia nigra'],roles:['Action selection','Movement','Habits','Learning'],desc:'Interconnected nuclei involved in action selection, movement, habits and reinforcement learning.'},
  brainstem:{name:'Brainstem',terms:['brainstem','midbrain','pons','medulla'],roles:['Arousal','Breathing','Cardiovascular','Reflexes'],desc:'Contains circuits involved in arousal, breathing, cardiovascular regulation and essential reflexes.'},
  cerebellum:{name:'Cerebellum',terms:['cerebellum','cerebellar hemisphere','vermis'],roles:['Coordination','Balance','Timing'],desc:'Coordinates movement and balance and contributes to timing, prediction and learning.'},
  motor:{name:'Motor cortex',terms:['precentral gyrus','motor cortex','primary motor'],roles:['Movement','Motor planning'],desc:'A key cortical system for planning and executing voluntary movement.'},
  sensory:{name:'Somatosensory cortex',terms:['postcentral gyrus','somatosensory','primary somatosensory'],roles:['Touch','Proprioception','Body map'],desc:'Represents touch, proprioception and other bodily sensory information.'},
  visual:{name:'Visual cortex',terms:['calcarine','visual cortex','occipital pole','cuneus','lingual gyrus'],roles:['Vision','Perception','Scene processing'],desc:'Processes visual information including objects, motion and spatial relationships.'},
  corpus:{name:'Corpus callosum',terms:['corpus callosum'],roles:['Interhemispheric communication'],desc:'A major fiber tract connecting the cerebral hemispheres.'}
};
const states={
  Neutral:{title:'Neutral',desc:'A reference state for exploring anatomy without a strong modeled demand.',roles:{pfc:'Adaptive',amygdala:'Background',hippocampus:'Adaptive',hypothalamus:'Background',thalamus:'Adaptive',insula:'Background',acc:'Adaptive',nacc:'Background',basal:'Adaptive',brainstem:'Background',cerebellum:'Adaptive',motor:'Background',sensory:'Background',visual:'Background',corpus:'Background'},body:'Balanced attention and autonomic demand in the educational reference model.'},
  Fear:{title:'Fear',desc:'A high-salience state that prioritizes threat detection, defensive readiness and context.',roles:{pfc:'Strained',amygdala:'Dominant',hippocampus:'Elevated',hypothalamus:'Elevated',thalamus:'Elevated',insula:'Elevated',acc:'Elevated',nacc:'Background',basal:'Elevated',brainstem:'Dominant',cerebellum:'Background',motor:'Elevated',sensory:'Elevated',visual:'Elevated',corpus:'Background'},body:'Threat-related processing can recruit autonomic and endocrine responses and bias attention toward salient cues.'},
  Stress:{title:'Stress',desc:'A high-demand state where threat, arousal and body-regulation systems can compete with executive control.',roles:{pfc:'Strained',amygdala:'Dominant',hippocampus:'Elevated',hypothalamus:'Dominant',thalamus:'Elevated',insula:'Elevated',acc:'Elevated',nacc:'Background',basal:'Elevated',brainstem:'Dominant',cerebellum:'Background',motor:'Elevated',sensory:'Elevated',visual:'Elevated',corpus:'Background'},body:'Stress can change autonomic and endocrine activity, vigilance, energy allocation and attention. Context and duration matter.'},
  Anger:{title:'Anger',desc:'A high-arousal state involving threat/salience, action readiness, valuation and regulation.',roles:{pfc:'Strained',amygdala:'Dominant',hippocampus:'Background',hypothalamus:'Elevated',thalamus:'Elevated',insula:'Elevated',acc:'Elevated',nacc:'Elevated',basal:'Dominant',brainstem:'Elevated',cerebellum:'Background',motor:'Dominant',sensory:'Elevated',visual:'Elevated',corpus:'Background'},body:'High arousal can mobilize energy for action while context and regulation shape behavior.'},
  Joy:{title:'Joy',desc:'A positive state emphasizing reward, motivation, social relevance and flexible engagement.',roles:{pfc:'Adaptive',amygdala:'Elevated',hippocampus:'Elevated',hypothalamus:'Adaptive',thalamus:'Adaptive',insula:'Elevated',acc:'Elevated',nacc:'Dominant',basal:'Elevated',brainstem:'Adaptive',cerebellum:'Adaptive',motor:'Elevated',sensory:'Elevated',visual:'Elevated',corpus:'Background'},body:'Positive affect can alter motivation, attention, autonomic state and social behavior.'},
  Sadness:{title:'Sadness',desc:'A state involving memory, appraisal, bodily awareness and changes in motivation.',roles:{pfc:'Adaptive',amygdala:'Elevated',hippocampus:'Dominant',hypothalamus:'Background',thalamus:'Background',insula:'Elevated',acc:'Dominant',nacc:'Background',basal:'Background',brainstem:'Background',cerebellum:'Background',motor:'Background',sensory:'Background',visual:'Elevated',corpus:'Background'},body:'Responses can change motivation, attention and social behavior and vary substantially by context.'},
  Love:{title:'Love / attachment',desc:'A social-reward state involving motivation, memory, salience and regulation.',roles:{pfc:'Adaptive',amygdala:'Elevated',hippocampus:'Elevated',hypothalamus:'Elevated',thalamus:'Adaptive',insula:'Elevated',acc:'Elevated',nacc:'Dominant',basal:'Elevated',brainstem:'Adaptive',cerebellum:'Background',motor:'Background',sensory:'Elevated',visual:'Elevated',corpus:'Background'},body:'Attachment and social reward can influence attention, motivation, autonomic state and memory.'},
  Focus:{title:'Focus',desc:'A state emphasizing sustained attention, executive control and goal-directed processing.',roles:{pfc:'Dominant',amygdala:'Background',hippocampus:'Elevated',hypothalamus:'Background',thalamus:'Elevated',insula:'Adaptive',acc:'Dominant',nacc:'Elevated',basal:'Elevated',brainstem:'Adaptive',cerebellum:'Adaptive',motor:'Background',sensory:'Elevated',visual:'Elevated',corpus:'Background'},body:'Focused attention changes how processing resources are allocated; arousal and motivation affect sustainability.'},
  Motivation:{title:'Motivation',desc:'A goal-directed state linking anticipated outcomes with effort, learning and action.',roles:{pfc:'Elevated',amygdala:'Adaptive',hippocampus:'Elevated',hypothalamus:'Adaptive',thalamus:'Background',insula:'Background',acc:'Elevated',nacc:'Dominant',basal:'Dominant',brainstem:'Adaptive',cerebellum:'Background',motor:'Elevated',sensory:'Background',visual:'Elevated',corpus:'Background'},body:'Motivation links valuation, reward prediction, executive control and action selection.'}
};
const networks={
  threat:{name:'Threat & salience',nodes:['amygdala','insula','acc','hypothalamus','brainstem'],desc:'Prioritizes biologically important signals and coordinates defensive or adaptive responses.',links:[['amygdala','insula'],['insula','acc'],['amygdala','hypothalamus'],['hypothalamus','brainstem'],['acc','brainstem']]},
  executive:{name:'Executive control',nodes:['pfc','acc','thalamus','basal'],desc:'Supports planning, attention, working memory, conflict monitoring and flexible action.',links:[['pfc','acc'],['pfc','thalamus'],['pfc','basal'],['acc','thalamus']]},
  reward:{name:'Reward & motivation',nodes:['nacc','basal','pfc','amygdala'],desc:'Links expected outcomes with motivation, effort, learning and action selection.',links:[['pfc','nacc'],['nacc','basal'],['amygdala','nacc'],['pfc','basal']]},
  memory:{name:'Memory & context',nodes:['hippocampus','pfc','amygdala','thalamus'],desc:'Links events with prior experience, context, emotion and retrieval.',links:[['hippocampus','amygdala'],['hippocampus','pfc'],['hippocampus','thalamus'],['amygdala','pfc']]},
  body:{name:'Brain–body regulation',nodes:['insula','hypothalamus','acc','brainstem','thalamus'],desc:'Integrates internal bodily signals with homeostatic, autonomic and attentional control.',links:[['insula','acc'],['insula','hypothalamus'],['hypothalamus','brainstem'],['thalamus','insula']]}
};
const factors={
  sleep:{name:'Sleep deprivation',delta:{pfc:'Strained',amygdala:'Elevated',hippocampus:'Strained',acc:'Strained'},text:'Reduced sleep can impair attention and executive control and alter emotional reactivity.'},
  exercise:{name:'Acute exercise',delta:{nacc:'Elevated',basal:'Elevated',brainstem:'Elevated',motor:'Elevated'},text:'Exercise changes arousal, autonomic state and neuromodulatory signaling; effects depend on intensity.'},
  meditation:{name:'Meditation',delta:{pfc:'Adaptive',amygdala:'Background',insula:'Elevated',acc:'Adaptive'},text:'Meditation practices can alter attention and regulation; effects vary by practice and person.'},
  caffeine:{name:'Caffeine',delta:{brainstem:'Elevated',pfc:'Elevated',thalamus:'Elevated'},text:'Caffeine increases alertness through adenosine-receptor antagonism; sensitivity varies.'},
  hunger:{name:'Hunger',delta:{hypothalamus:'Dominant',insula:'Elevated',nacc:'Elevated',pfc:'Strained'},text:'Energy status is monitored through hypothalamic and peripheral signals that influence motivation.'},
  rejection:{name:'Social rejection',delta:{amygdala:'Elevated',insula:'Dominant',acc:'Elevated',nacc:'Background'},text:'Social threat can recruit salience, interoceptive and control systems; context strongly shapes the response.'},
  novelty:{name:'Novelty',delta:{hippocampus:'Elevated',thalamus:'Elevated',nacc:'Elevated',acc:'Elevated'},text:'Novel events recruit attention, learning and valuation systems.'},
  chronic:{name:'Prolonged stress',delta:{pfc:'Strained',amygdala:'Dominant',hypothalamus:'Dominant',hippocampus:'Strained',acc:'Strained'},text:'Longer-term stress exposure can affect multiple regulatory systems; human effects are heterogeneous.'}
};
const meditations={
  breath:{name:'Breath-focused',desc:'Sustained attention on breathing with repeated redirection when attention wanders.',emphasis:['pfc','acc','insula'],waves:{delta:15,theta:45,alpha:70,beta:30,gamma:15}},
  open:{name:'Open monitoring',desc:'Broad, non-reactive awareness of thoughts, sensations and external events.',emphasis:['insula','acc','pfc','thalamus'],waves:{delta:18,theta:58,alpha:78,beta:24,gamma:22}},
  loving:{name:'Loving-kindness',desc:'Cultivates warm, affiliative attention toward self and others.',emphasis:['nacc','acc','insula','pfc'],waves:{delta:15,theta:52,alpha:74,beta:28,gamma:38}},
  body:{name:'Body scan',desc:'Moves attention through bodily sensations and interoceptive awareness.',emphasis:['insula','thalamus','acc'],waves:{delta:20,theta:62,alpha:76,beta:20,gamma:18}}
};

const $=id=>document.getElementById(id); const stage=$('stage');
let scene,camera,renderer,controls,brainRoot,raycaster,mouse,animationId;
let meshes=[],meshByRegion={},selectedRegion='pfc',hoverRegion=null;
let state='Neutral', intensity=70, activeNetwork=null, activeFactors=new Set(), view='anatomy', connectionsOn=false, labelsOn=false, regionsOn=true, hemisphere='both', cortexOpacity=.62;
let meditationKey='breath', meditationMinutes=10, simulationMode='emotion';
let connectionGroup=new THREE.Group();
const statusForRole={Dominant:{class:'dominant',icon:'●'},Elevated:{class:'elevated',icon:'●'},Strained:{class:'strained',icon:'◆'},Adaptive:{class:'adaptive',icon:'●'},Background:{class:'background',icon:'○'}};

function normalize(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ')}
function regionForObject(obj){const n=normalize(obj.name); for(const [id,r] of Object.entries(anatomy)){if(r.terms.some(t=>n.includes(normalize(t)))) return id} return null}
function initScene(){
  scene=new THREE.Scene(); scene.background=new THREE.Color(0x071019); camera=new THREE.PerspectiveCamera(35,1,.01,100); camera.position.set(0,0.25,7.2);
  renderer=new THREE.WebGLRenderer({canvas:$('brainCanvas'),antialias:true,alpha:false,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75)); renderer.setSize(10,10,false); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.1;
  controls=new OrbitControls(camera,$('brainCanvas')); controls.enableDamping=true; controls.dampingFactor=.06; controls.minDistance=3.8; controls.maxDistance=12; controls.enablePan=true;
  scene.add(new THREE.HemisphereLight(0xb9d7e8,0x101820,1.5)); const l=new THREE.DirectionalLight(0xffffff,2.5); l.position.set(4,5,7); scene.add(l); const l2=new THREE.DirectionalLight(0x6eb9ff,1.3); l2.position.set(-5,1,-4); scene.add(l2); scene.add(connectionGroup);
  raycaster=new THREE.Raycaster(); mouse=new THREE.Vector2();
  $('brainCanvas').addEventListener('pointermove',onPointerMove); $('brainCanvas').addEventListener('pointerdown',onPointerDown); window.addEventListener('resize',resize);
  animate();
}
function resize(){if(!renderer)return; const r=$('brainCanvas').getBoundingClientRect(); if(r.width<1||r.height<1)return; renderer.setSize(r.width,r.height,false); camera.aspect=r.width/r.height; camera.updateProjectionMatrix()}
function loadModel(){
  const loader=new GLTFLoader(); const draco=new DRACOLoader(); draco.setDecoderPath(DRACO_URL); draco.setDecoderConfig({type:'js'}); loader.setDRACOLoader(draco);
  loader.load(MODEL_URL,g=>{brainRoot=g.scene; scene.add(brainRoot); brainRoot.traverse(o=>{if(!o.isMesh)return; const region=regionForObject(o); const n=normalize(o.name); const isCortex=/gyrus|sulcus|cortex|lobe|pole|precuneus|cuneus|lingual|fusiform|operculum|lobule/.test(n); o.userData.region=region; o.userData.isCortex=isCortex; o.userData.baseMaterial=o.material; o.material=o.material.clone(); o.material.transparent=true; o.material.depthWrite=true; meshes.push(o); if(region)(meshByRegion[region]??=[]).push(o);}); frameBrain(); $('loadCard').style.display='none'; $('loadStatus').textContent='Ready'; renderInspector(); renderLabels(); updateVisuals();},xhr=>{if(xhr.total){const p=Math.round(xhr.loaded/xhr.total*100); $('progressBar').style.width=p+'%'; $('loadStatus').textContent=`Loading anatomy… ${p}%`;}else{$('loadStatus').textContent='Loading anatomy…';}},err=>{console.error(err); $('loadCard').style.display='none'; $('stageError').classList.add('show'); $('errorText').textContent='The anatomical model could not be loaded. The app is still intact; use Retry to attempt the asset again.'});
}
function frameBrain(){if(!brainRoot)return; const box=new THREE.Box3().setFromObject(brainRoot); const size=box.getSize(new THREE.Vector3()); const center=box.getCenter(new THREE.Vector3()); brainRoot.position.sub(center); const max=Math.max(size.x,size.y,size.z); const dist=max/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2)))*.9; camera.position.set(0,max*.05,Math.max(5,dist)); camera.near=.01;camera.far=100;camera.updateProjectionMatrix();controls.target.set(0,0,0);controls.update()}
function stateRole(id){
  if(simulationMode==='meditation'){
    const em=meditations[meditationKey]?.emphasis||[];
    if(em.includes(id)) return meditationMinutes>=20?'Elevated':'Adaptive';
    if(['amygdala','hypothalamus','brainstem'].includes(id)) return meditationMinutes>=15?'Background':'Adaptive';
    return 'Background';
  }
  let role=states[state]?.roles[id]||'Background'; for(const key of activeFactors){const f=factors[key]; if(f.delta[id])role=f.delta[id]} return role
}
function roleColor(role){return {Dominant:new THREE.Color('#ed6574'),Elevated:new THREE.Color('#ee985c'),Strained:new THREE.Color('#f2c86b'),Adaptive:new THREE.Color('#61d39b'),Background:new THREE.Color('#748692')}[role]||new THREE.Color('#748692')}
function updateVisuals(){if(!brainRoot)return; meshes.forEach(m=>{const id=m.userData.region; const role=id?stateRole(id):'Background'; const c=id?roleColor(role):new THREE.Color('#71828e'); const selected=id===selectedRegion; const hovered=id===hoverRegion; let opacity=m.userData.isCortex?cortexOpacity:(regionsOn?.9:0); if(hemisphere!=='both'){const n=normalize(m.name); const isLeft=n.includes(' left')||n.startsWith('left '); const isRight=n.includes(' right')||n.startsWith('right '); if((hemisphere==='left'&&isRight)||(hemisphere==='right'&&isLeft))opacity=0}else if(activeNetwork && id && !networks[activeNetwork].nodes.includes(id)){opacity*=.22}
  m.visible=opacity>.01; if(m.visible){m.material.opacity=opacity; m.material.color.copy(c); m.material.emissive.copy(c); m.material.emissiveIntensity=selected?.55:hover?.32:.08; m.material.roughness=.55; m.material.metalness=.02;}
 }); updateConnections(); updateLabels(); $('stateChip').textContent=simulationMode==='meditation'?`MEDITATION · ${meditationMinutes} MIN`:state.toUpperCase(); $('modePill').textContent=view.toUpperCase(); $('selectionPill').textContent=hoverRegion?anatomy[hoverRegion].name:(selectedRegion?anatomy[selectedRegion].name:'Hover a structure');}
function regionCenter(id){const arr=meshByRegion[id]; if(!arr?.length)return null; const box=new THREE.Box3(); arr.forEach(m=>box.expandByObject(m)); return box.getCenter(new THREE.Vector3())}
function updateConnections(){connectionGroup.clear(); if(!connectionsOn||!brainRoot)return; let pairs=[]; if(activeNetwork)pairs=networks[activeNetwork].links; else if(selectedRegion){const r=selectedRegion; Object.values(networks).forEach(n=>n.links.forEach(p=>{if(p.includes(r)&&!pairs.some(x=>x[0]===p[0]&&x[1]===p[1]))pairs.push(p)}))}
  pairs.forEach(([a,b])=>{const p1=regionCenter(a),p2=regionCenter(b);if(!p1||!p2)return; const mid=p1.clone().add(p2).multiplyScalar(.5); mid.y+=Math.max(.15,p1.distanceTo(p2)*.12); const curve=new THREE.CatmullRomCurve3([p1,mid,p2]); const geo=new THREE.TubeGeometry(curve,24,.018,7,false); const mat=new THREE.MeshBasicMaterial({color:activeNetwork?'#79d8ff':'#9ed8e8',transparent:true,opacity:activeNetwork?.72:.42}); const line=new THREE.Mesh(geo,mat); connectionGroup.add(line)});
}
function renderLabels(){document.querySelectorAll('.brain-label').forEach(e=>e.remove()); if(!labelsOn||!brainRoot)return; Object.entries(meshByRegion).forEach(([id,arr])=>{const p=regionCenter(id); if(!p)return; const el=document.createElement('div'); el.className='brain-label'; el.dataset.region=id; el.textContent=anatomy[id].name; el.style.cssText='position:absolute;pointer-events:none;background:rgba(5,12,18,.78);border:1px solid rgba(255,255,255,.12);padding:4px 6px;border-radius:6px;font-size:9px;color:#eef4f8;transform:translate(-50%,-50%);display:none;z-index:3'; stage.appendChild(el); el._world=p; }); positionLabels()}
function positionLabels(){if(!brainRoot)return; const rect=$('brainCanvas').getBoundingClientRect(); document.querySelectorAll('.brain-label').forEach(el=>{const p=el._world.clone().project(camera); el.style.left=(rect.left+((p.x+1)/2)*rect.width-stage.getBoundingClientRect().left)+'px'; el.style.top=(rect.top+((1-p.y)/2)*rect.height-stage.getBoundingClientRect().top)+'px'; el.style.display=(p.z>-1&&p.z<1)?'block':'none';})}
function onPointerMove(e){const r=$('brainCanvas').getBoundingClientRect(); mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(meshes,false);const id=hits.length?hits[0].object.userData.region:null;if(id!==hoverRegion){hoverRegion=id;updateVisuals()}}
function onPointerDown(e){if(e.button!==0)return; const r=$('brainCanvas').getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(meshes,false);if(hits.length){selectedRegion=hits[0].object.userData.region;renderInspector();updateVisuals()}}
function renderInspector(){const r=anatomy[selectedRegion]; if(view==='states'){renderStateInspector();return} if(view==='scenarios'){renderScenarioInspector();return} if(view==='networks'){renderNetworkInspector();return} if(view==='learn'){renderLearnInspector();return} if(!r){$('inspectorContent').innerHTML='<p class="copy">Hover or select a brain structure.</p>';return} $('inspectorContent').innerHTML=`<div class="eyebrow">Selected structure</div><h2>${r.name}</h2><p class="copy">${r.desc}</p><h3>Key roles</h3><div class="tags">${r.roles.map(x=>`<span class="tag">${x}</span>`).join('')}</div><h3>In ${state}</h3><div class="mini-row"><span>Functional emphasis</span><strong class="${statusForRole[stateRole(selectedRegion)].class}">${stateRole(selectedRegion)}</strong></div><div class="callout">${whyFor(selectedRegion,state)}</div><h3>Explore connections</h3><div class="tags">${connectionNames(selectedRegion).map(x=>`<span class="tag">${x}</span>`).join('')}</div>`}
function whyFor(id,s){const map={Stress:{amygdala:'Threat/salience is prioritized in this high-demand state.',pfc:'Executive regulation is under greater demand while threat and arousal systems are prominent.',hypothalamus:'Links stress-related signals with autonomic and endocrine regulation.',brainstem:'Supports arousal and autonomic readiness.',insula:'Bodily signals become more salient.',hippocampus:'Context and prior experience help shape the meaning of the stressor.'}}; return map[s]?.[id]||`${anatomy[id].name} has a ${stateRole(id).toLowerCase()} role in the current educational model.`}
function connectionNames(id){const set=new Set();Object.values(networks).forEach(n=>n.links.forEach(p=>{if(p.includes(id)){const other=p[0]===id?p[1]:p[0];set.add(anatomy[other].name)}}));return [...set]}
function renderStateInspector(){
  if(simulationMode==='meditation'){
    const m=meditations[meditationKey];
    const bandValues=Object.fromEntries(Object.entries(m.waves).map(([k,v])=>[k,Math.max(5,Math.min(95,Math.round(v + (meditationMinutes-10)*({delta:-.05,theta:.28,alpha:.42,beta:-.22,gamma:.16}[k]))))]));
    $('inspectorContent').innerHTML=`<div class="eyebrow">Meditation</div><h2>${m.name}</h2><p class="copy">${m.desc}</p><h3>Time</h3><input id="medTimeInspector" type="range" min="1" max="60" value="${meditationMinutes}" style="width:100%;accent-color:var(--accent)"><div class="mini-row"><span>1 min</span><b id="medTimeValue">${meditationMinutes} min</b><span>60 min</span></div><h3>Brain emphasis</h3>${m.emphasis.map(id=>`<div class="mini-row"><span>${anatomy[id].name}</span><strong class="adaptive">${stateRole(id)}</strong></div>`).join('')}<h3>EEG bands</h3><div class="tags">${Object.entries(bandValues).map(([k,v])=>`<span class="tag">${k} · illustrative ${v}%</span>`).join('')}</div><div class="callout">EEG patterns during meditation vary by practice, expertise and person. These bands are an educational visualization, not a live EEG reading.</div>`;
    $('medTimeInspector').addEventListener('input',e=>{meditationMinutes=Number(e.target.value);$('medTimeValue').textContent=meditationMinutes+' min';updateVisuals();renderInspector()});
    return;
  }
  const s=states[state];const groups=[['Threat / salience',['amygdala','insula','acc']],['Autonomic / body',['hypothalamus','brainstem','thalamus']],['Control / context',['pfc','hippocampus','acc']],['Reward / action',['nacc','basal','motor']]]; $('inspectorContent').innerHTML=`<div class="eyebrow">${s.title}</div><h2>${s.title}</h2><p class="copy">${s.desc}</p><h3>State balance</h3>${groups.map(([name,ids])=>{const counts=ids.map(id=>stateRole(id));const rank=['Dominant','Elevated','Strained','Adaptive','Background'];const strongest=counts.sort((a,b)=>rank.indexOf(a)-rank.indexOf(b))[0];return `<div class="mini-row"><span>${name}</span><strong class="${statusForRole[strongest].class}">${strongest}</strong></div>`}).join('')}<h3>Brain → body</h3><div class="callout">${s.body}</div><h3>Intensity</h3><input id="inspectorIntensity" type="range" min="0" max="100" value="${intensity}" style="width:100%;accent-color:var(--accent)"><div class="mini-row"><span>Lower demand</span><b id="inspectorIntensityValue">${intensity}%</b><span>Higher demand</span></div>`; const inp=$('inspectorIntensity'); if(inp)inp.addEventListener('input',e=>{intensity=Number(e.target.value);$('stateChip').textContent=state.toUpperCase();$('inspectorIntensityValue').textContent=intensity+'%';updateVisuals()})}
function renderScenarioInspector(){const selected=[...activeFactors].map(k=>factors[k].name);$('inspectorContent').innerHTML=`<div class="eyebrow">Scenario</div><h2>${selected.length?'Active scenario':'Build a scenario'}</h2><p class="copy">Combine conditions, then apply them to the brain.</p><h3>Selected</h3><div class="tags">${selected.length?selected.map(x=>`<span class="tag">${x}</span>`).join(''):'<span class="tag">None yet</span>'}</div><h3>Readout</h3><div class="callout">${selected.length?[...activeFactors].map(k=>factors[k].text).join(' '):'Choose factors in the Scenario Builder panel.'}</div><div class="apply-row"><button class="btn primary" id="openScenario">Choose factors</button><button class="btn" id="clearScenario">Reset</button></div>`; $('openScenario')?.addEventListener('click',()=>openDrawer('scenarios'));$('clearScenario')?.addEventListener('click',()=>{activeFactors.clear();activeNetwork=null;updateVisuals();renderInspector()})}
function renderNetworkInspector(){const n=activeNetwork?networks[activeNetwork]:null;$('inspectorContent').innerHTML=n?`<div class="eyebrow">Network</div><h2>${n.name}</h2><p class="copy">${n.desc}</p><h3>Core structures</h3><div class="tags">${n.nodes.map(id=>`<span class="tag">${anatomy[id].name}</span>`).join('')}</div><h3>Visualization</h3><div class="callout">The highlighted pathways show the selected network. Other anatomy stays visible but is subdued.</div><div class="apply-row"><button class="btn primary" id="showNetworkLinks">${connectionsOn?'Connections on':'Show connections'}</button><button class="btn" id="clearNetwork">Clear</button></div>`:'<div class="eyebrow">Brain networks</div><h2>Choose a network</h2><p class="copy">Select a network to highlight its structures and pathways.</p>'; $('showNetworkLinks')?.addEventListener('click',()=>{connectionsOn=true;$('connectionsBtn').classList.add('active');updateVisuals();renderInspector()});$('clearNetwork')?.addEventListener('click',()=>{activeNetwork=null;connectionsOn=false;updateVisuals();renderInspector()})}
function renderLearnInspector(){const lessons=[['distributed','Distributed processing','See how one state can involve multiple interacting systems.'],['context','Context matters','Compare memory, threat and executive systems.'],['body','Brain ↔ body','Follow hypothalamus, brainstem and insula.'],['plasticity','Plasticity','See how experience can change neural organization over time.']];$('inspectorContent').innerHTML=`<div class="eyebrow">Learn</div><h2>Learn through the brain</h2><p class="copy">Choose a concept and the 3-D model will demonstrate it.</p><h3>Lessons</h3><div class="tags">${lessons.map(([id,t])=>`<button class="btn lessonPick" data-lesson="${id}" style="margin:3px 0;width:100%;text-align:left">${t}</button>`).join('')}</div><div id="lessonMini" class="callout" style="margin-top:10px">Choose a lesson.</div>`;document.querySelectorAll('.lessonPick').forEach(b=>b.addEventListener('click',()=>applyLesson(b.dataset.lesson)))}
function applyLesson(id){activeNetwork=id==='distributed'?'threat':id==='context'?'memory':id==='body'?'body':null;connectionsOn=Boolean(activeNetwork); if(id==='plasticity'){state='Neutral';activeFactors.clear();activeNetwork='memory';connectionsOn=true} updateVisuals();renderInspector();openDrawer('learn',id)}
function openDrawer(type,sub){view=type;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===type));$('drawer').classList.add('open');$('drawerEyebrow').textContent=type==='states'?'State lab':type==='scenarios'?'Scenario builder':type==='networks'?'Brain networks':type==='learn'?'Learn':'Anatomy';$('drawerTitle').textContent=type==='states'?'Emotional states':type==='scenarios'?'Build a scenario':type==='networks'?'Choose a network':type==='learn'?'Learn through the brain':''; if(type==='states')renderStatesDrawer();if(type==='scenarios')renderScenarioDrawer();if(type==='networks')renderNetworksDrawer();if(type==='learn')renderLearnDrawer(sub)}
function closeDrawer(){ $('drawer').classList.remove('open'); view='anatomy'; document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view==='anatomy')); renderInspector(); updateVisuals()}
function renderStatesDrawer(){const names=Object.keys(states);$('drawerContent').innerHTML=`<div class="seg" style="margin-bottom:12px"><button id="emotionModeBtn" class="${simulationMode==='emotion'?'active':''}">Emotions</button><button id="meditationModeBtn" class="${simulationMode==='meditation'?'active':''}">Meditation</button></div><div id="stateDrawerBody"></div>`; const body=$('stateDrawerBody'); if(simulationMode==='meditation'){renderMeditationDrawer(body);return;} body.innerHTML=`<div class="grid">${names.map(s=>`<div class="card ${s===state?'selected':''}"><button data-state-card="${s}"><h3>${s}</h3><p>${states[s].desc}</p></button></div>`).join('')}</div><div style="margin-top:12px" class="card"><h3>Intensity</h3><input id="drawerIntensity" type="range" min="0" max="100" value="${intensity}" style="width:100%;accent-color:var(--accent)"><div class="mini-row"><span>Lower</span><b id="drawerIntensityValue">${intensity}%</b><span>Higher</span></div></div>`;document.querySelectorAll('[data-state-card]').forEach(b=>b.addEventListener('click',()=>{state=b.dataset.stateCard;simulationMode='emotion';activeNetwork=null;document.querySelectorAll('[data-state-card]').forEach(x=>x.closest('.card').classList.toggle('selected',x===b));renderInspector();updateVisuals();}));$('drawerIntensity').addEventListener('input',e=>{intensity=Number(e.target.value);$('drawerIntensityValue').textContent=intensity+'%';renderInspector();updateVisuals()}); $('emotionModeBtn').addEventListener('click',()=>{simulationMode='emotion';renderStatesDrawer();renderInspector();updateVisuals()}); $('meditationModeBtn').addEventListener('click',()=>{simulationMode='meditation';renderStatesDrawer();renderInspector();updateVisuals()})}
function renderMeditationDrawer(body){body.innerHTML=`<div class="grid">${Object.entries(meditations).map(([k,m])=>`<div class="card ${k===meditationKey?'selected':''}"><button data-med=${k}><h3>${m.name}</h3><p>${m.desc}</p></button></div>`).join('')}</div><div class="card" style="margin-top:12px"><h3>Time meditated</h3><input id="medTimeDrawer" type="range" min="1" max="60" value="${meditationMinutes}" style="width:100%;accent-color:var(--accent)"><div class="mini-row"><span>1 min</span><b id="medTimeDrawerValue">${meditationMinutes} min</b><span>60 min</span></div><h3>Illustrative EEG bands</h3><div class="wave" id="waveViz"></div><div class="tags" style="margin-top:8px">${Object.entries(meditations[meditationKey].waves).map(([k,v])=>{const vv=Math.max(5,Math.min(95,Math.round(v + (meditationMinutes-10)*({delta:-.05,theta:.28,alpha:.42,beta:-.22,gamma:.16}[k]))));return `<span class="tag">${k} · ${vv}%</span>`}).join('')}</div></div>`;document.querySelectorAll('[data-med]').forEach(b=>b.addEventListener('click',()=>{meditationKey=b.dataset.med;renderMeditationDrawer(body);renderInspector();updateVisuals()}));$('medTimeDrawer').addEventListener('input',e=>{meditationMinutes=Number(e.target.value);$('medTimeDrawerValue').textContent=meditationMinutes+' min';renderInspector();updateVisuals()}); const w=$('waveViz'); w.innerHTML=Array.from({length:32},(_,i)=>`<i style="height:${12+((i*17+meditationMinutes*3)%45)}px"></i>`).join('')}
function renderScenarioDrawer(){const cats=Object.entries(factors);$('drawerContent').innerHTML=`<p class="copy">Choose the conditions you want to combine. Nothing changes until you press Apply to brain.</p><div class="factor-grid" style="margin-top:12px">${cats.map(([k,f])=>`<button class="factor ${activeFactors.has(k)?'active':''}" data-factor="${k}">${f.name}<small>${f.text}</small></button>`).join('')}</div><div class="card" style="margin-top:12px"><h3>Selected</h3><div id="scenarioSelected" class="tags"></div><div class="apply-row"><button class="btn primary" id="applyScenario">Apply to brain</button><button class="btn" id="resetScenario">Reset</button></div></div>`;document.querySelectorAll('[data-factor]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.factor;activeFactors.has(k)?activeFactors.delete(k):activeFactors.add(k);b.classList.toggle('active',activeFactors.has(k));renderScenarioSelected()}));function renderScenarioSelected(){$('scenarioSelected').innerHTML=[...activeFactors].map(k=>`<span class="tag">${factors[k].name}</span>`).join('')||'<span class="tag">None</span>'}renderScenarioSelected();$('applyScenario').addEventListener('click',()=>{state='Stress';simulationMode='emotion';activeNetwork=null;connectionsOn=false;$('drawer').classList.remove('open');view='scenarios';document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view==='scenarios'));renderInspector();updateVisuals()});$('resetScenario').addEventListener('click',()=>{activeFactors.clear();renderScenarioDrawer();updateVisuals()})}
function renderNetworksDrawer(){ $('drawerContent').innerHTML=Object.entries(networks).map(([k,n])=>`<div class="network-row"><button data-network="${k}"><strong>${n.name}</strong><p>${n.desc}</p></button><span>›</span></div>`).join('');document.querySelectorAll('[data-network]').forEach(b=>b.addEventListener('click',()=>{activeNetwork=b.dataset.network;connectionsOn=true;selectedRegion=networks[activeNetwork].nodes[0];closeDrawer();view='networks';document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view==='networks'));renderInspector();updateVisuals()}))}
function renderLearnDrawer(sub){const lessons=[['distributed','Distributed processing','A state emerges from interacting systems rather than one “emotion center”.'],['context','Context matters','Memory and expectations change how signals are interpreted.'],['body','Brain ↔ body','The brain and body continuously exchange information.'],['plasticity','Plasticity','Experience can change neural function and connectivity over time.']];$('drawerContent').innerHTML=`<div class="lesson-stage">${lessons.map(([id,t,d])=>`<div class="lesson-step ${sub===id?'active':''}"><h3>${t}</h3><p>${d}</p><button class="btn" data-learn="${id}" style="margin-top:9px">Show on brain</button></div>`).join('')}</div>`;document.querySelectorAll('[data-learn]').forEach(b=>b.addEventListener('click',()=>{applyLesson(b.dataset.learn);closeDrawer()}))}
function setView(v){if(v==='anatomy'){closeDrawer();return}view=v;openDrawer(v);renderInspector()}
function resetAll(){state='Neutral';intensity=70;simulationMode='emotion';meditationKey='breath';meditationMinutes=10;activeNetwork=null;activeFactors.clear();selectedRegion='pfc';hoverRegion=null;connectionsOn=false;labelsOn=false;regionsOn=true;hemisphere='both';cortexOpacity=.62;$('connectionsBtn').classList.remove('active');$('labelsBtn').classList.remove('active');$('regionsBtn').classList.add('active');$('bothBtn').classList.add('active');$('leftBtn').classList.remove('active');$('rightBtn').classList.remove('active');$('cortexOpacity').value=62;$('opacityValue').textContent='62%';closeDrawer();frameBrain();renderInspector();updateVisuals()}
function animate(){animationId=requestAnimationFrame(animate);if(controls)controls.update();if(brainRoot)brainRoot.rotation.y+=.00025;positionLabels();if(renderer&&scene&&camera)renderer.render(scene,camera)}

// UI wiring
for(const n of document.querySelectorAll('.nav'))n.addEventListener('click',()=>setView(n.dataset.view));
$('drawerClose').addEventListener('click',closeDrawer);$('resetAll').addEventListener('click',resetAll);$('aboutBtn').addEventListener('click',()=>{$('aboutModal').style.display='flex'});$('aboutClose').addEventListener('click',()=>{$('aboutModal').style.display='none'});$('aboutModal').addEventListener('click',e=>{if(e.target===$('aboutModal'))$('aboutModal').style.display='none'});
$('regionsBtn').addEventListener('click',()=>{regionsOn=!regionsOn;$('regionsBtn').classList.toggle('active',regionsOn);updateVisuals()});
$('connectionsBtn').addEventListener('click',()=>{connectionsOn=!connectionsOn;$('connectionsBtn').classList.toggle('active',connectionsOn);updateVisuals()});
$('labelsBtn').addEventListener('click',()=>{labelsOn=!labelsOn;$('labelsBtn').classList.toggle('active',labelsOn);renderLabels()});
$('bothBtn').addEventListener('click',()=>{hemisphere='both';document.querySelectorAll('#bothBtn,#leftBtn,#rightBtn').forEach(x=>x.classList.remove('active'));$('bothBtn').classList.add('active');updateVisuals()});$('leftBtn').addEventListener('click',()=>{hemisphere='left';document.querySelectorAll('#bothBtn,#leftBtn,#rightBtn').forEach(x=>x.classList.remove('active'));$('leftBtn').classList.add('active');updateVisuals()});$('rightBtn').addEventListener('click',()=>{hemisphere='right';document.querySelectorAll('#bothBtn,#leftBtn,#rightBtn').forEach(x=>x.classList.remove('active'));$('rightBtn').classList.add('active');updateVisuals()});
$('cortexOpacity').addEventListener('input',e=>{cortexOpacity=Number(e.target.value)/100;$('opacityValue').textContent=e.target.value+'%';updateVisuals()});$('retryBtn').addEventListener('click',()=>{location.reload()});
const quick=['Fear','Stress','Joy','Love','Focus','Motivation'];$('quickStates').innerHTML=quick.map(s=>`<button class="chip" data-quick="${s}">${s}</button>`).join('');document.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>{state=b.dataset.quick;openDrawer('states');renderInspector();updateVisuals()}));
$('searchInput').addEventListener('input',e=>{const q=normalize(e.target.value);const matches=q?[...new Set(meshes.filter(m=>normalize(m.name).includes(q)||anatomy[m.userData.region].name.toLowerCase().includes(q)).map(m=>m.userData.region))]:[];if(!q){$('searchResults').classList.remove('show');return}$('searchResults').innerHTML=matches.slice(0,10).map(id=>`<button class="result" data-search-region="${id}">${anatomy[id].name}</button>`).join('')||'<div class="result">No matching major region</div>';$('searchResults').classList.add('show');document.querySelectorAll('[data-search-region]').forEach(b=>b.addEventListener('click',()=>{selectedRegion=b.dataset.searchRegion;$('searchInput').value=anatomy[selectedRegion].name;$('searchResults').classList.remove('show');view='anatomy';closeDrawer();renderInspector();updateVisuals()}))});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('aboutModal').style.display==='flex')$('aboutModal').style.display='none';else closeDrawer()}});

initScene();loadModel();
